# ~/.tmux.conf

# Install
#
# curl -sL https://gist.github.com/zthxxx/bbbb37c100254d688236c21e8b977b85/raw/.tmux.conf -o ~/.tmux.conf
#

######################

#
# -- Common Settings --
#

# Enable xterm keys to correctly interpret key sequences
setw -g xterm-keys on

# Eliminate delay for escape key sequences
set -s escape-time 0

# Set the rate for repeating keys when held down
set -sg repeat-time 300

# Enable focus events for terminal
set -s focus-events on

# Enable mouse support
set-option -g mouse on

# Automatically exit tmux when there are no sessions
set -sg exit-empty on

# Quietly enable UTF-8 support for status line
set -q -g status-utf8 on

# Quietly enable UTF-8 support for windows
setw -q -g utf8 on

# Disable visual notification for window activity
set -g visual-activity off

# Disable monitoring of window activity
setw -g monitor-activity off

# Disable bell notification for the window
setw -g monitor-bell off

# scroll history cache
set -g history-limit 65535

#
# -- Prefix key --
#
unbind C-b
set -g prefix 'C-s'

#
# -- Window display --
#

# Set the base index for windows to 1 instead of the default 0
set -g base-index 1

# Set the base index for panes to 1 instead of the default 0
setw -g pane-base-index 1

# Enable automatic renaming of windows based on the running application
setw -g automatic-rename on

# Automatically renumber the windows to have sequential indices after a window is closed
set -g renumber-windows on

# Automatically set terminal title to reflect the current program and directory
set -g set-titles on

# Display pane numbers for 2000 milliseconds (2 seconds) when the display-panes command is used
set -g display-panes-time 2000

# Display messages for 2000 milliseconds (2 seconds)
set -g display-time 2000

# Update status line every 1 second
set -g status-interval 1



# Shortcut Key binding

# bind Alt + [123...=] to window 1~12
# `M` is `Meta key`

bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9
bind -n M-0 select-window -t :10

bind -n 'M-!' join-pane -t :1
bind -n 'M-@' join-pane -t :2
bind -n 'M-#' join-pane -t :3
bind -n 'M-$' join-pane -t :4
bind -n 'M-%' join-pane -t :5
bind -n 'M-^' join-pane -t :6
bind -n 'M-&' join-pane -t :7
bind -n 'M-*' join-pane -t :8
bind -n 'M-(' join-pane -t :9

# new panel in current window,
# the new panel position like:
#
#     I
#  J  K  L
#
bind i split-window -vb -c "#{pane_current_path}"
bind k split-window -v -c "#{pane_current_path}"
bind j split-window -hb -c "#{pane_current_path}"
bind l split-window -h -c "#{pane_current_path}"


bind -n F2 previous-window
bind -n F3 next-window

bind -n F5 new-window -c "#{pane_current_path}"
bind -n F6 detach
bind -n F7 kill-window

# bind F8 to rename current tmux window
bind -n F8 command-prompt "rename-window %%"

# bind F12 to toggle mouse scoll modle On/Off
bind -n F12 "display 'Turn Mouse #{?mouse,OFF,ON}'; set-option mouse #{?mouse,off,on};"


#
# -- theme --
#

# Status bar background to black
set -g status-bg black
## this set background to transparent
## set-option -g status-style "bg=default,bg=default"

# Status bar left to show Session Name
set -g status-left-length 60
set-option -g status-left "#[fg=gray]Session: #S | "


# Status bar right to show Hostname and Time
set -g status-right-length 60
set-option -g status-right "#[fg=gray] #H | %Y-%m-%d %H:%M:%S"


# windows
# set -g status-justify 'centre'
setw -g window-status-format '#[fg=brightblue] #I #W'
setw -g window-status-current-format '#[fg=magenta,bold] [#I #W:#F]'
# setw -g window-status-separator ''


